### ISSUE TITLE
Compilation fails with current Makefile

### ISSUE THREAD

**Issue by btoninho** [andrejbauer/spartan-type-theory#3]
Hi,

Wanted to report that with current versions of sedlex (at least on my machine) compilation will not work unless the Makefile line is changed from:

    OCAMLBUILD_FLAGS = -j 4 -cflags -w,+a-4-27-29-50,"-warn-error +a" -lib unix -use-ocamlfind -pkg menhirLib -pkg sedlex

to

    OCAMLBUILD_FLAGS = -j 4 -cflags -w,+a-4-27-29-50,"-warn-error +a" -lib unix -use-ocamlfind -pkg menhirLib -pkg sedlex.ppx

**Comment by andrejbauer** [comment]
Yeah, I know of the problem, it's causing trouble in a couple of other repositories. I am still looking for a stable solution. Do you know which versio of sedlex switched from `sedlex` to `sedlex.ppx`?

**Comment by btoninho** [comment]
Sadly no. Was just trying to compile your implementation and eventually found the fix.
